apiVersion: v1
kind: Service
metadata:
  name: gestion-stock-api-service
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
  selector:
    app: gestion-stock-api
  type: LoadBalancer

