apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql
spec: 
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      volumes:
        - name: data
          hostPath:
            path: /gestionstock/namespaces/db
      containers: 
        - 
          image: "mysql:8.0"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          imagePullPolicy: IfNotPresent
          name: mysql
          ports: 
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: gestionstock
              